### ISSUE TITLE
Handle absecnce of .bumpit.yaml with clean error

### ISSUE THREAD

**Issue by josemanimala** [mobiusbyte/bumpit#11]
**Describe the bug**
Bumpit when invoked without the `.bumpit.yaml` file gives a file not found error. 

**To Reproduce**
1. `pip install bumpit`
2. `bumpit -d`

**Expected behavior**
No error, just help text saying file is missing. 

**Additional context**
```
Traceback (most recent call last):
  File "/home/jose/.virtualenvs/build_tools/bin/bumpit", line 8, in <module>
    sys.exit(main())
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/bumpit/console/cli.py", line 48, in main
    bumpit()  # pragma: no cover
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/bumpit/console/cli.py", line 26, in bumpit
    configuration = Configuration.parse(config)
  File "/home/jose/.virtualenvs/build_tools/lib/python3.7/site-packages/bumpit/core/config.py", line 15, in parse
    with open(file, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '.bumpit.yaml'
```

**Comment by iamjillsanluis** [comment]
I have updated the code to check for the file. Since the fix uses Click feature, there was no need to test it. 

After running it manually, the output rendered
```
(mobiusbyte) bash-3.2$ bumpit
Usage: bumpit [OPTIONS]
Try "bumpit --help" for help.

Error: Invalid value for "--config" / "-c": Path ".bumpit.yaml" does not exist.
```
